apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry-service
spec:
  type: LoadBalancer
  selector:
    app: registry-service  
  ports:
  - port: 8761
  externalIPs:
  - 172.17.0.30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service
  labels:
    app: registry-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
      - name: registry-service
        image: dockrtraining/registry-service
        ports:
        - containerPort: 8761
