apiVersion: v1
kind: Service
metadata:
  name: registry-service-nodeport
  namespace: shopping-cart
spec:
  type: NodePort
  selector:
    app: registry-service
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 8761
    targetPort: 8761
