version: '3.3'
services:
  databases:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"
  web:
    image: nginx
    ports:
    - "80:80"    